### ISSUE TITLE
Text will not render

### ISSUE THREAD

**Issue by Raynesz** [MrVallentin/glText#14]
I have  a C++ project using OpenGL 3.3 / GLFW / glad to render graphics and i am trying to run your example but have no text showing when i run my program. I am using Visual Studio 2019 and the gltext.h is included properly. I get no errors whatsoever.
Could there be a problem with another graphics draw call cutting the text out? Thanks in advance!

**Comment by vallentin** [comment]
Just to clarify, when you say "trying to run your example". Do you mean that you're running the examples/simple.c as is? or that you took part of the code into your own project?

**Comment by Raynesz** [comment]
`
// The app will use the main GPU installed on the system
#include <windows.h>
#ifdef __cplusplus
extern "C" {
#endif

	__declspec(dllexport) DWORD NvOptimusEnablement = 1;
	__declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;

#ifdef __cplusplus
}
#endif

#include "Game.h"

#define GLT_IMPLEMENTATION
#include "gltext.h" /* https://github.com/vallentin/glText */

if (!gltInit())
{
	fprintf(stderr, "Failed to initialize glText\n");
	glfwTerminate();
	return EXIT_FAILURE;
}

GLTtext* text1 = gltCreateText();
gltSetText(text1, "Hello World!");

int main() {
	Viewer viewer(WINDOW_NAME);
	ImGuiIO& io = UI::Initialize(viewer.window);

	Game game(viewer);

	glfwSetWindowUserPointer(viewer.window, &game);
	glfwSetKeyCallback(viewer.window, key_callback);

	srand(time(NULL));
	game.InitializeResources();
	game.Setup(4);

	// Main while loop
	while (!glfwWindowShouldClose(viewer.window))
	{
		// INPUT
		// Take care of all GLFW events
		glfwPollEvents();

		game.controlsActive = !game.windowsOpen() && glfwGetWindowAttrib(viewer.window, GLFW_FOCUSED);

		if (game.controlsActive) {
			if (!io.WantCaptureMouse) { // Game input is disabled if mouse is hovering over UI elements
				viewer.Inputs();
				// Handles camera inputs (delete this if you have disabled VSync)
				if (!game.camera.locked) game.camera.Inputs(viewer.window, viewer.dt);
				// Updates and exports the camera matrix to the Vertex Shader
				game.Inputs();
			}
		}
		game.camera.updateMatrix(45.0f, 0.1f, 1000.0f);

		if (game.camera.type != CLICK_FPV) {
			if (game.controlsActive) glfwSetInputMode(viewer.window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN);
			else glfwSetInputMode(viewer.window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
		}

		// UPDATE
		game.Update();

		// RENDER
		// Specify the color of the background
		glClearColor(game.clearColor.r, game.clearColor.g, game.clearColor.b, game.clearColor.a);
		// Clean the back buffer and depth buffer
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

		UI::NewFrame();
		
		game.Draw();

		game.DrawUI(io);
		UI::Render();

               gltBeginDraw();

		gltColor(1.0f, 1.0f, 1.0f, 1.0f);
		gltDrawText2D(text1, 0.0f, 0.0f, 1.0f); // x=0.0, y=0.0, scale=1.0

		gltDrawText2DAligned(text1,
			(GLfloat)(viewer.width / 2),
			(GLfloat)(viewer.height / 2),
			3.0f,
			GLT_CENTER, GLT_CENTER);

               gltEndDraw();

		viewer.FpsCounter();

		// Swap the back buffer with the front buffer
		glfwSwapBuffers(viewer.window);
	}

        gltDeleteText(text1);

	gltTerminate();

	game.CleanUp();
	UI::Terminate();

	return 0;
}
`
This will not render text on screen. I just took text1, not text2 or the time, although I tried all of them before. Viewer initializes glfw and glad and the entire 3D scene renders properly except the text. I also receive no errors which means that everything compiles. I dont know if it matters but im also using ImGUI in the project and I dont know if there is any weird interaction between the two. For example, I know ImGUI can affect a few things like the mouse cursor. My main suspicion is that it might have to do with the z-buffer (renders everything over the text?). I should also add that all headers that you use are included in Game.h. Let me know if there is anything else I can tell you about the project.

**Comment by Raynesz** [comment]
Please disregard the code in the previous comment. i ll attach my main.cpp here
[main.txt](https://github.com/vallentin/glText/files/7295719/main.txt)

**Comment by Raynesz** [comment]
Finally found the culprit. It seems the quads/triangles are drawn backwards. I am drawing everything with `glFrontFace(GL_CCW);` and for the text I had to swap to `glFrontFace(GL_CW);`.
